# Generated by Django 4.0.4 on 2022-05-22 15:06

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_state', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StatesPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statepago', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UploadDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Document', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('Description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date_first', models.DateField()),
                ('date_finish', models.DateField()),
                ('cost_total', models.DecimalField(decimal_places=3, default=0, max_digits=9)),
                ('Doc_propuesta', models.ManyToManyField(blank=True, to='work.uploaddoc')),
                ('Encargado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work.encargado')),
                ('Residencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.people')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado', to='work.states')),
                ('state_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='work.statespago')),
            ],
        ),
    ]
