# Generated by Django 4.0.4 on 2022-05-22 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='Residencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='place.place'),
        ),
    ]
