# Generated by Django 4.0.4 on 2022-05-22 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_alter_place_representante'),
        ('work', '0002_alter_people_residencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='Encargado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.encargado'),
        ),
        migrations.AlterField(
            model_name='people',
            name='Residencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='place.place'),
        ),
    ]
