# Generated by Django 4.0.4 on 2022-05-22 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_alter_place_representante'),
        ('work', '0003_alter_people_encargado_alter_people_residencia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='People',
            new_name='Work',
        ),
    ]
