# Generated by Django 4.0.4 on 2022-05-22 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_residence', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=9)),
                ('addres', models.CharField(max_length=15)),
                ('Representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peoples', to='people.people')),
            ],
        ),
    ]
