# Generated by Django 4.0.4 on 2022-05-22 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='Representante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peoples', to='people.people'),
        ),
    ]
