# Generated by Django 4.0.4 on 2022-05-08 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
                ('productDescription', models.TextField(blank=True)),
                ('productPrice', models.DecimalField(decimal_places=0, default=0, max_digits=9)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-productName'],
            },
        ),
        migrations.CreateModel(
            name='ProductSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='residence.product')),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boxName', models.CharField(max_length=255)),
                ('product_set', models.ManyToManyField(to='residence.productset')),
            ],
        ),
    ]
