# Generated by Django 4.0.4 on 2022-05-08 01:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleSex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sex', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SignaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=9)),
                ('addres', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('date_birth', models.DateField(blank=True)),
                ('email', models.CharField(max_length=35)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sexo', to='people.peoplesex')),
                ('signature', models.ManyToManyField(blank=True, to='people.signaimage')),
            ],
        ),
    ]
