# Generated by Django 4.0.4 on 2022-05-20 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=9)),
                ('cost_product', models.DecimalField(decimal_places=0, default=0, max_digits=9)),
                ('cost_sales', models.DecimalField(decimal_places=0, default=0, max_digits=9)),
                ('sku', models.CharField(max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productscategory')),
                ('image', models.ManyToManyField(blank=True, to='products.productsimage')),
            ],
        ),
    ]
